using Ray.BiliBiliTool.Agent.BiliBiliAgent.Dtos;
using Refit;

namespace Ray.BiliBiliTool.Agent.BiliBiliAgent.Interfaces;

/// <summary>
/// Device fingerprint endpoints on api.bilibili.com
/// </summary>
[Headers("Host: api.bilibili.com")]
public interface IGaiaApi
{
    /// <summary>
    /// Get the web device fingerprint cookies bound to the current session.
    /// </summary>
    /// <remarks>Returns a fresh buvid3/buvid4 pair that still has no server-side profile.</remarks>
    [Headers("Referer: https://www.bilibili.com/", "Origin: https://www.bilibili.com")]
    [Get("/x/frontend/finger/spi")]
    Task<BiliApiResponse<DeviceFingerprintResponse>> GetDeviceFingerprint(
        [Header("Cookie")] string ck
    );

    /// <summary>
    /// Report the web device fingerprint (ExClimbWuzhi).
    /// </summary>
    /// <remarks>
    /// A buvid3 generated by the program has no server-side device profile, and using it
    /// directly makes share and other endpoints fail with -403 "account abnormal".
    /// The device must be reported once through this endpoint to create the profile.
    /// The User-Agent must match the template device features; GaiaDeviceFingerprintTemplate.UserAgent
    /// is a compile-time constant, so it can be concatenated here. The gaia client is registered
    /// without the global UA on purpose (see Agent/Extensions/ServiceCollectionExtension).
    /// Verified against the production container on 2026-09-15: a generated buvid3 plus this
    /// report makes share/add pass.
    /// </remarks>
    [Headers(
        "Referer: https://www.bilibili.com/",
        "Origin: https://www.bilibili.com",
        "User-Agent: " + GaiaDeviceFingerprintTemplate.UserAgent
    )]
    [Post("/x/internal/gaia-gateway/ExClimbWuzhi")]
    Task<BiliApiResponse<object>> ReportDeviceFingerprint(
        [Header("Cookie")] string ck,
        [Body] GaiaReportRequest request
    );
}
