const CryptoJS = require('crypto-js');
const md5 = (str) => CryptoJS.MD5(str).toString(CryptoJS.enc.Hex);

const MIXIN_KEY_ENC_TAB = [
  46, 47, 18,  2, 53,  8, 23, 32, 15, 50, 10, 31, 58,  3, 45, 35,
  27, 43,  5, 49, 33,  9, 42, 19, 29, 28, 14, 39, 12, 38, 41, 13,
  37, 48,  7, 16, 24, 55, 40, 61, 26, 17,  0,  1, 60, 51, 30,  4,
  22, 25, 54, 21, 56, 59,  6, 63, 57, 62, 11, 36, 20, 34, 44, 52,
];

/**
 * Derive mixin key from imgKey + subKey concatenated string (64 chars).
 * Picks chars at MIXIN_KEY_ENC_TAB indices and takes first 32 chars.
 */
function getMixinKey(orig) {
  return MIXIN_KEY_ENC_TAB.map(i => orig[i]).join('').slice(0, 32);
}

/**
 * Extract key from a wbi img/sub URL like:
 *   https://i0.hdslb.com/bfs/wbi/7cd084941338484aae1ad9425b84077d.png
 * → "7cd084941338484aae1ad9425b84077d"
 */
function extractKeyFromUrl(url) {
  return url.split('/').pop().replace(/\.\w+$/, '');
}

/**
 * Sign query params with WBI.
 * @param {object} params  - key/value pairs (will be mutated to add wts & w_rid)
 * @param {string} imgKey
 * @param {string} subKey
 */
function encWbi(params, imgKey, subKey) {
  const mixinKey = getMixinKey(imgKey + subKey);
  const wts = Math.floor(Date.now() / 1000);
  const chrFilter = /[!'()*]/g;

  const signed = { wts: String(wts) };
  for (const [k, v] of Object.entries(params)) {
    signed[encodeURIComponent(k)] = encodeURIComponent(String(v).replace(chrFilter, ''));
  }

  const query = Object.keys(signed).sort()
    .map(k => `${k}=${signed[k]}`)
    .join('&');

  const w_rid = md5(query + mixinKey);
  return { wts, w_rid };
}

/**
 * Fetch WBI keys from Bilibili nav API, then sign query params of the request.
 * Replaces `wts` and `w_rid` query params in-place.
 *
 * Usage in Bruno pre-request script:
 *   const { signWbi } = require('./lib/wbi');
 *   await signWbi(req, bru);
 */
async function signWbi(req, bru) {
  const cookieStr = bru.getEnvVar('cookieStr') || bru.getVar('cookieStr') || '';

  // Fetch WBI keys from /nav
  const navRes = await fetch('https://api.bilibili.com/x/web-interface/nav', {
    headers: {
      Cookie: cookieStr,
      'User-Agent': bru.getEnvVar('user-agent-web') || 'Mozilla/5.0',
      Referer: 'https://www.bilibili.com/',
    },
  });
  const navJson = await navRes.json();

  const wbiImg = navJson?.data?.wbi_img;
  if (!wbiImg) throw new Error('WBI: failed to get wbi_img from /nav');

  const imgKey = extractKeyFromUrl(wbiImg.img_url);
  const subKey = extractKeyFromUrl(wbiImg.sub_url);

  // Parse query params from the request URL.
  // At pre-request time, Bruno has NOT yet resolved {{placeholders}}, so we
  // resolve them manually here before signing.
  const url = req.getUrl();
  const qIdx = url.indexOf('?');
  const qs = qIdx !== -1 ? url.slice(qIdx + 1) : '';
  const params = {};
  if (qs) {
    qs.split('&').forEach(pair => {
      const eqIdx = pair.indexOf('=');
      if (eqIdx === -1) return;
      const k = decodeURIComponent(pair.slice(0, eqIdx));
      const v = decodeURIComponent(pair.slice(eqIdx + 1));
      // Skip wts / w_rid — will be generated by encWbi
      if (k === 'wts' || k === 'w_rid') return;
      // Resolve {{placeholder}}
      params[k] = v.replace(/\{\{(.*?)\}\}/g, (_, name) =>
        bru.getVar(name) ?? bru.getEnvVar(name) ?? ''
      );
    });
  }

  const { wts, w_rid } = encWbi(params, imgKey, subKey);

  // Only inject the two signed vars — Bruno fills {{wts}} and {{w_rid}} in the
  // params list from these vars, so no URL rebuild is needed.
  bru.setVar('wts', String(wts));
  bru.setVar('w_rid', w_rid);
  console.log(`WBI signed — wts: ${wts}, w_rid: ${w_rid}`);
}

module.exports = { getMixinKey, extractKeyFromUrl, encWbi, signWbi };
