name: Moderate comments
on: [issue_comment, pull_request_review]

jobs:
  check-comment-toxicity:
    runs-on: ubuntu-latest
    name: Check comments for toxicity
    steps:
      - uses: actions/checkout@v7
      - name: Safe space - action step
        uses: charliegerard/safe-space@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}